# Generated by Django 5.0.7 on 2024-08-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailystock',
            table='daily_stock',
        ),
    ]
